retrofit:
  naver:
    url: https://openapi.naver.com/
    client:
      id: OKy2xFauYpeFR1WYcoJ_
      secret: q7KrGmcqCg
  kakao:
    url: https://dapi.kakao.com/
    client:
      key: b637d7bc7cb7cdc6baebe0a8d996b923

spring:
  redis:
    host: redis-server
    port: 6379
